version: '3.8'

services:
  crawler_pusher:
    build: .
    environment:
      - CRAWLBASE_API_KEY=${CRAWLBASE_API_KEY}
    volumes:
      - .:/app
    command: ruby /app/scripts/crawler_pusher.rb
    depends_on:
      - crawler_puller

  crawler_puller:
    build: .
    environment:
      - CRAWLBASE_API_KEY=${CRAWLBASE_API_KEY}
    volumes:
      - .:/app
    command: ruby /app/scripts/crawler_puller.rb

  crawler_exporter:
    build: .
    volumes:
      - .:/app
    command: /bin/sh -c "sleep 120 && ruby /app/scripts/crawler_exporter.rb"
    depends_on:
      - crawler_puller
