version: '3.8'

services:
  crawler_pusher:
    build: .
    environment:
      - CRAWLBASE_API_KEY=${CRAWLBASE_API_KEY}
    volumes:
      - .:/app
    command: ruby /app/scripts/crawler_pusher.rb

  crawler_puller:
    build: .
    environment:
      - CRAWLBASE_API_KEY=${CRAWLBASE_API_KEY}
    volumes:
      - .:/app
    command: ruby /app/scripts/crawler_puller.rb

  crawler_exporter:
    build: .
    volumes:
      - .:/app
    command: ruby /app/scripts/crawler_exporter.rb
